/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hanaa
 */
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.text.DateFormat;
public class NewJFrame extends javax.swing.JFrame {
//private Passengers passengers;
//private Flight flights;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addPassenger = new javax.swing.JButton();
        customerName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        submitBookingButton = new javax.swing.JButton();
        passengerCombo = new javax.swing.JComboBox<>();
        flightCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookingText = new javax.swing.JTextPane();
        dateCombo = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        statusFlightCombo = new javax.swing.JComboBox<>();
        statusFlightdate = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        checkFlightStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightStatusText = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        statusWaitlistDate = new javax.swing.JComboBox<>();
        waitlistStatus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        waitlistText = new javax.swing.JTextArea();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        addDayText = new javax.swing.JTextField();
        addDayButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        flightnameText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        seatText = new javax.swing.JTextField();
        addFlightButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cancelText = new javax.swing.JTextArea();
        cancelPassenger = new javax.swing.JComboBox<>();
        cancelDate = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        customerStatusText = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        customerStatusCombo = new javax.swing.JComboBox<>();
        customerStatusButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        dropButton = new javax.swing.JButton();
        dropCombo = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        dropText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 2, 36)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        jTabbedPane1.setForeground(new java.awt.Color(0, 153, 204));
        jTabbedPane1.setToolTipText("");

        jLabel2.setText("Name: ");

        addPassenger.setText("Add Passenger");
        addPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPassengerActionPerformed(evt);
            }
        });

        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addPassenger))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(addPassenger)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Passenger", jPanel1);

        submitBookingButton.setText("Submit Booking");
        submitBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBookingButtonActionPerformed(evt);
            }
        });

        passengerCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                passengerComboPopupMenuWillBecomeVisible(evt);
            }
        });
        passengerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerComboActionPerformed(evt);
            }
        });

        flightCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                flightComboPopupMenuWillBecomeVisible(evt);
            }
        });
        flightCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Passenger:");

        jLabel4.setText("Flight: ");

        jLabel5.setText("Date:");

        BookingText.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jScrollPane2.setViewportView(BookingText);

        dateCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                dateComboPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(submitBookingButton)
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(flightCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 71, Short.MAX_VALUE)
                    .addComponent(passengerCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(submitBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        jLabel9.setText("Flight:");

        statusFlightCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                statusFlightComboPopupMenuWillBecomeVisible(evt);
            }
        });

        statusFlightdate.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                statusFlightdatePopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel10.setText("Date:");

        checkFlightStatus.setText("Check Status");
        checkFlightStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFlightStatusActionPerformed(evt);
            }
        });

        flightStatusText.setColumns(20);
        flightStatusText.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        flightStatusText.setRows(5);
        jScrollPane1.setViewportView(flightStatusText);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(statusFlightdate, 0, 77, Short.MAX_VALUE)
                                    .addComponent(statusFlightCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(checkFlightStatus)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusFlightdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addComponent(checkFlightStatus)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Flight Status", jPanel5);

        jLabel11.setText("Date: ");

        statusWaitlistDate.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                statusWaitlistDatePopupMenuWillBecomeVisible(evt);
            }
        });

        waitlistStatus.setText("Check Waitlist Status");
        waitlistStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistStatusActionPerformed(evt);
            }
        });

        waitlistText.setColumns(20);
        waitlistText.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        waitlistText.setRows(5);
        jScrollPane3.setViewportView(waitlistText);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(50, 50, 50)
                        .addComponent(statusWaitlistDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(waitlistStatus)))
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusWaitlistDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(42, 42, 42)
                .addComponent(waitlistStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Waitlist Status", jPanel6);

        jTabbedPane1.addTab("Status", jTabbedPane2);

        jLabel8.setText("Date:");

        addDayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayTextActionPerformed(evt);
            }
        });

        addDayButton.setText("Add Day");
        addDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("format: YYYY-MM-DD ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8)
                        .addGap(64, 64, 64)
                        .addComponent(addDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(addDayButton)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(112, 112, 112)
                .addComponent(addDayButton)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Day", jPanel3);

        jLabel6.setText("Flight:");

        jLabel7.setText("Seat:");

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seatText, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(flightnameText)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(addFlightButton)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(flightnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(seatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(addFlightButton)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Flight", jPanel4);

        jTabbedPane1.addTab("Add", jTabbedPane3);

        jLabel13.setText("Passenger:");

        jLabel14.setText("Date:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        cancelText.setColumns(20);
        cancelText.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        cancelText.setRows(5);
        jScrollPane4.setViewportView(cancelText);

        cancelPassenger.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cancelPassengerPopupMenuWillBecomeVisible(evt);
            }
        });

        cancelDate.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cancelDatePopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelDate, 0, 81, Short.MAX_VALUE)
                    .addComponent(cancelPassenger, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(274, 274, 274))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(cancelButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cancelPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Cancel", jPanel7);

        customerStatusText.setColumns(20);
        customerStatusText.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        customerStatusText.setRows(5);
        jScrollPane5.setViewportView(customerStatusText);

        jLabel15.setText("Passenger:");

        customerStatusCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                customerStatusComboPopupMenuWillBecomeVisible(evt);
            }
        });

        customerStatusButton.setText("Check Status");
        customerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel15)
                                .addGap(83, 83, 83)
                                .addComponent(customerStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(customerStatusButton)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(customerStatusButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Customer Status", jPanel8);

        jLabel16.setText("Flight Number:");

        dropButton.setText("Drop");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        dropCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                dropComboPopupMenuWillBecomeVisible(evt);
            }
        });
        dropCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropComboActionPerformed(evt);
            }
        });

        dropText.setColumns(20);
        dropText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        dropText.setRows(5);
        jScrollPane6.setViewportView(dropText);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel16)
                        .addGap(81, 81, 81)
                        .addComponent(dropCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(dropButton))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dropCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(dropButton)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Drop Flight", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waitlistStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistStatusActionPerformed
        // TODO add your handling code here:
        int num = statusWaitlistDate.getSelectedIndex();
        Dates statusD = Dates.getDateList().get(num);
        ArrayList<String> name = new ArrayList<String>();
        name = Waitlist.statusWaitlistDay(statusD.getDate());
        waitlistText.setText(null);
        for (String s : name) {
            //  System.out.print(s);
            waitlistText.append(s + "\n");
        }
    }//GEN-LAST:event_waitlistStatusActionPerformed

    private void statusWaitlistDatePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_statusWaitlistDatePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Dates d : Dates.getDateList()){
            //System.out.print(d.getDate());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateStr = sdf.format(d.getDate());
            strings.add(dateStr);}
        //}
        statusWaitlistDate.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_statusWaitlistDatePopupMenuWillBecomeVisible

    private void checkFlightStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFlightStatusActionPerformed
        // TODO add your handling code here:
        int num = statusFlightCombo.getSelectedIndex();
        int num2 = statusFlightdate.getSelectedIndex();
        Flight checkF = Flight.getFlightList().get(num);
        Dates checkD = Dates.getDateList().get(num2);
        ArrayList<String> name = new ArrayList<String>();
        name = Booking.statusFlightDay(checkD.getDate(), checkF.getFlightName());
        flightStatusText.setText(null);
        flightStatusText.setText("Booked:" + "\n");
        for (String s : name) {
            //  System.out.print(s);
            flightStatusText.append(s + "\n");
        }

    }//GEN-LAST:event_checkFlightStatusActionPerformed

    private void statusFlightdatePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_statusFlightdatePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Dates d : Dates.getDateList()){
            //System.out.print(d.getDate());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateStr = sdf.format(d.getDate());
            strings.add(dateStr);}
        //}
        statusFlightdate.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_statusFlightdatePopupMenuWillBecomeVisible

    private void statusFlightComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_statusFlightComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Flight f : Flight.getFlightList()){
            //System.out.print(f.getFlightName());
            strings.add(f.getFlightName());
        }
        statusFlightCombo.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_statusFlightComboPopupMenuWillBecomeVisible

    private void dateComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_dateComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Dates d : Dates.getDateList()){
            //System.out.print(d.getDate());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateStr = sdf.format(d.getDate());
            strings.add(dateStr);}
        //}
        dateCombo.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_dateComboPopupMenuWillBecomeVisible

    private void flightComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboActionPerformed

    private void flightComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_flightComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Flight f : Flight.getFlightList()){
            //System.out.print(f.getFlightName());
            strings.add(f.getFlightName());
        }
        flightCombo.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_flightComboPopupMenuWillBecomeVisible

    private void passengerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerComboActionPerformed

    private void passengerComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_passengerComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Passengers p : Passengers.getPassengerList()){
            //System.out.print(p.getName());
            strings.add(p.getName());
        }
        passengerCombo.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_passengerComboPopupMenuWillBecomeVisible

    private void submitBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBookingButtonActionPerformed
        // TODO add your handling code here:
        int num =  flightCombo.getSelectedIndex();
        int num2 = dateCombo.getSelectedIndex();
        int num3 = passengerCombo.getSelectedIndex();
        Flight chooseF = Flight.getFlightList().get(num);
        Dates chooseD = Dates.getDateList().get(num2);
        Passengers chooseP = Passengers.getPassengerList().get(num3);
        int seatF = chooseF.getFlightSeat();
        //System.out.print(seatF);
        int seatB = Booking.getFlightSeats(chooseF.getFlightName(), chooseD.getDate());
        //System.out.print(seatB);
        if (seatF > seatB){
            Booking.addBooking(chooseD.getDate(), chooseP.getName(), chooseF.getFlightName());
            BookingText.setText("You are booked!");
        }
        else{
            Waitlist.getWaitList(chooseF.getFlightName(), chooseD.getDate(), chooseP.getName());
            BookingText.setText("You've been added to the waitlist.");
        }
    }//GEN-LAST:event_submitBookingButtonActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
        //String b = evt.getActionCommand();
        //passengers.setName(b);
        //System.out.print(b);

    }//GEN-LAST:event_customerNameActionPerformed

    private void addPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPassengerActionPerformed
        // TODO add your handling code here:
        //String a = customerName.getText();
        Passengers.addPassenger(customerName.getText());
        //passengerCombo.addItem(customerName.getText());
        JOptionPane.showMessageDialog(null,"You've successfully added a passenger.");
    }//GEN-LAST:event_addPassengerActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
        Flight.addFlight(flightnameText.getText(),Integer.parseInt(seatText.getText()));
        JOptionPane.showMessageDialog(null,"You've successfully added a flight.");
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void addDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayButtonActionPerformed
        // TODO add your handling code here:
       Date addDate = java.sql.Date.valueOf(addDayText.getText());
       Dates.addDate(addDate);
       JOptionPane.showMessageDialog(null,"You've successfully added a date.");
       //Exception
       
    }//GEN-LAST:event_addDayButtonActionPerformed

    private void cancelPassengerPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cancelPassengerPopupMenuWillBecomeVisible
        // TODO add your handling code here:
         ArrayList<String> strings = new ArrayList<String>();
        for (Passengers p : Passengers.getPassengerList()){
            //System.out.print(p.getName());
            strings.add(p.getName());
        }
        cancelPassenger.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_cancelPassengerPopupMenuWillBecomeVisible

    private void cancelDatePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cancelDatePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ArrayList<String> strings = new ArrayList<String>();
        for (Dates d : Dates.getDateList()){
            //System.out.print(d.getDate());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateStr = sdf.format(d.getDate());
            strings.add(dateStr);}
        //}
        cancelDate.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_cancelDatePopupMenuWillBecomeVisible

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int num2 = cancelDate.getSelectedIndex();
        int num3 = cancelPassenger.getSelectedIndex();
        String addP = null;
        Dates chooseD = Dates.getDateList().get(num2);
        Passengers chooseP = Passengers.getPassengerList().get(num3);
        if (Booking.checkBooking(chooseD.getDate(),chooseP.getName())){
            //System.out.print(Booking.getFlight(chooseD.getDate(),chooseP.getName()));
           addP = Waitlist.addtoBooking(Booking.getFlight(chooseD.getDate(),chooseP.getName()), chooseD.getDate());
            Booking.removeBooking(chooseD.getDate(),chooseP.getName());
            cancelText.setText("The scheduled flight has been cancelled for " + chooseP.getName() + "\n" +
                addP + "  " + "has been booked from waitlist");
        }
        else{
            Waitlist.removeWaitlist(chooseD.getDate(),chooseP.getName());
            cancelText.setText(chooseP.getName() + " " + "has been removed from waitlist.");
        }
            
            
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void customerStatusComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_customerStatusComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
         ArrayList<String> strings = new ArrayList<String>();
        for (Passengers p : Passengers.getPassengerList()){
            //System.out.print(p.getName());
            strings.add(p.getName());
        }
        customerStatusCombo.setModel(new DefaultComboBoxModel(strings.toArray()));
    }//GEN-LAST:event_customerStatusComboPopupMenuWillBecomeVisible

    private void customerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerStatusButtonActionPerformed
        // TODO add your handling code here:
        int num = customerStatusCombo.getSelectedIndex();
        Passengers chooseP = Passengers.getPassengerList().get(num);
        ArrayList<String> statusB = new ArrayList<String>();
        statusB =  Booking.customerStatusBooking(chooseP.getName());
        ArrayList<String> statusW = new ArrayList<String>();
        statusW =  Waitlist.customerStatusWaitlist(chooseP.getName());
        customerStatusText.setText(null);
        customerStatusText.setText("Booking:" + "\n");
        for (String s : statusB) {
            //  System.out.print(s);
            customerStatusText.append(s + "\n");
        }
       customerStatusText.append("Waitlist:" + "\n");
        for (String s : statusW) {
            //  System.out.print(s);
            customerStatusText.append(s + "\n");
        }
    }//GEN-LAST:event_customerStatusButtonActionPerformed

    private void dropComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropComboActionPerformed

    private void dropComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_dropComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
         ArrayList<String> strings = new ArrayList<String>();
        for (Flight f : Flight.getFlightList()){
            //System.out.print(f.getFlightName());
            strings.add(f.getFlightName());
        }
        dropCombo.setModel(new DefaultComboBoxModel(strings.toArray()));
                           
    }//GEN-LAST:event_dropComboPopupMenuWillBecomeVisible

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
        dropText.setText(null);
        int num = dropCombo.getSelectedIndex();
        //dropText.setText(null);
        Flight chooseF = Flight.getFlightList().get(num);
        for (String s : Waitlist.waitlist_dropFlight_name(chooseF.getFlightName())) {
            //  System.out.print(s);
            dropText.append(s + "\n");
        }
        //Waitlist.waitlist_dropFlight(chooseF.getFlightName());
        ArrayList<String> a = Passengers.passenger_dropFlight(chooseF.getFlightName());
        Flight.flight_dropFlight(chooseF.getFlightName());
        ArrayList<Flight> b = Flight.getFlightList();
        for (String passenger : a){
            boolean addtoBooking = false;
            String[] pd = passenger.split(",");
            String name = pd[0];
            Date flight_date = java.sql.Date.valueOf(pd[1]);
            //System.out.print(pd[1]);
            for (Flight flight : b){
                int seatF = flight.getFlightSeat();
                int seatB = Booking.getFlightSeats(flight.getFlightName(),flight_date);
                if (seatF > seatB){
               addtoBooking = true;
               Booking.removeBooking(flight_date, name); //delete old booking
               Booking.addBooking(flight_date, name, flight.getFlightName());
               dropText.append(name + " " + "has been booked for" + "  " + flight.getFlightName()+ "  " + "on" + " " + flight_date + "\n");
               break;
            }
                else{
                    continue;
                }
            }
            if (addtoBooking == false){
          Booking.removeBooking(flight_date, name);
         dropText.append(name + " " + "has been cancelled from bookings" + "  " + flight_date + "\n");
        }
        }
    }//GEN-LAST:event_dropButtonActionPerformed

    private void addDayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDayTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane BookingText;
    private javax.swing.JButton addDayButton;
    private javax.swing.JTextField addDayText;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JButton addPassenger;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cancelDate;
    private javax.swing.JComboBox<String> cancelPassenger;
    private javax.swing.JTextArea cancelText;
    private javax.swing.JButton checkFlightStatus;
    private javax.swing.JTextField customerName;
    private javax.swing.JButton customerStatusButton;
    private javax.swing.JComboBox<String> customerStatusCombo;
    private javax.swing.JTextArea customerStatusText;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JButton dropButton;
    private javax.swing.JComboBox<String> dropCombo;
    private javax.swing.JTextArea dropText;
    private javax.swing.JComboBox<String> flightCombo;
    private javax.swing.JTextArea flightStatusText;
    private javax.swing.JTextField flightnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> passengerCombo;
    private javax.swing.JTextField seatText;
    private javax.swing.JComboBox<String> statusFlightCombo;
    private javax.swing.JComboBox<String> statusFlightdate;
    private javax.swing.JComboBox<String> statusWaitlistDate;
    private javax.swing.JButton submitBookingButton;
    private javax.swing.JButton waitlistStatus;
    private javax.swing.JTextArea waitlistText;
    // End of variables declaration//GEN-END:variables
}
